---
    - name: Avocado EPEL Copr repo
      yum_repository:
        name: avocado-latest
        description: Copr repo for avocado-latest
        baseurl: https://copr-be.cloud.fedoraproject.org/results/@avocado/avocado-latest/epel-7-$basearch/
        gpgcheck: no
      when:
        - ansible_facts['distribution_file_variety'] == "RedHat"
        - ansible_facts['distribution_major_version'] == "7"
    - name: Avocado Fedora Copr repo
      yum_repository:
        name: avocado-latest
        description: Copr repo for avocado-latest
        baseurl: https://copr-be.cloud.fedoraproject.org/results/@avocado/avocado-latest/fedora-$releasever-$basearch/
        gpgcheck: no
      when:
        - ansible_facts['distribution'] == "Fedora"
